# START_KITTY_THEME
include theme.conf
# END_KITYY_THEME

# Terminal Background
background_opacity 0.8
background #1B0623

# Font settings
# font_family      Gohu Mono 11 Nerd Font
# bold_font        Gohu Mono 11 Nerd Font Bold
# italic_font      Gohu Mono 11 Nerd Font
# bold_italic_font Gohu Mono 11 Nerd Font Bold


# BEGIN_KITTY_FONTS
font_family      family="GohuFont 11 Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
shell ~/.local/bin/kitty-zellij

# Cursor Behavior 
cursor_stop_blinking_after 60
