#  Font
font_family "GohuFont Mono 11 Nerd Font" 
bold_font auto
italic_font auto
bold_italic_font auto
#  Default font size
font_size 13
#  Change font size
map ctrl+shift_plus change_font_size all +1.0
map ctrl+shift_minus change_font_size all -1.0  
#
#  Cursor shape
#shell_intergration no-cursor
cursor_shape beam 
#
#  Padding
window_padding_width 5
window_padding_height 5px
#
#  Background opacity, set to 0 if you want transparancy
background_opacity 1

#  Colors
#  cursor
#
#  selection_background
#  selection_forground
#
#  background
#  foreground
#
#  color0
#  color1
#  color2
#  color3
#  color4
#  color5
#  color6
#  color7
#  color8
#
#  Scroll back up to x lines
scrollback_lines 10000
#  
#   
